# BSD 3-Clause License
# Copyright (c) 2022, GM Consult Pty Ltd
# All rights reserved.

name: free_text_search
description: Search an inverted positional index and return ranked references to documents relevant to the search phrase.
version: 0.0.1-beta.6
publish_to: none
repository: https://github.com/GM-Consult-Pty-Ltd/free_text_search
homepage: https://github.com/GM-Consult-Pty-Ltd
issue_tracker: https://github.com/GM-Consult-Pty-Ltd/free_text_search/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  # -----PubDev Packages (in alphabetic order) -----
  collection: ^1.17.0
  rxdart: ^0.27.5
  text_indexing:
    git: https://github.com/GM-Consult-Pty-Ltd/text_indexing.git

  # text_indexing: ^0.22.4

dev_dependencies:
  gmconsult_dev: ^0.0.7
  hive: ^2.2.3
  hive_text_index: 
    git: https://github.com/GM-Consult-Pty-Ltd/hive_text_index.git
  lints: ^2.0.1
  test: ^1.22.0
  
